- name: "Copy httpd Configuration file"
  ansible.builtin.copy:
    src: files/httpd.original
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: '0644'
  notify:
  - restart apache

