---
- name: Play1 - Install misl softwares, Apache and tomcat
  hosts: webservers
  become: yes
  vars:
    v_roles_path: "{{ WORKSPACE }}/roles"
  roles:
    - "{{ v_roles_path }}/misl"
    - "{{ v_roles_path }}/apache"
    - "{{ v_roles_path }}/tomcat"

- name: Play2 - Custom configuration of apache code
  hosts: webservers
  become: yes
  tasks:
    - name: remove existing document root
      ansible.builtin.file: 
        path: /var/www/html
        state: absent

    - name: code copy
      ansible.builtin.git:
        repo: https://github.com/Sukesh5186/java-db-Login.git
        dest: /var/www/html
        version: ansible-project
        force: yes

    - name: copy proxypass file
      ansible.builtin.copy:
        src: "{{ WORKSPACE }}/proxypass.conf"
        dest: /etc/httpd/conf.d/proxypass.conf
        owner: root
        group: root
      notify:
        - reload apache

    - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
      ansible.posix.seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
      tags: setsebool

  handlers:
    - name: reload apache
      ansible.builtin.service: name=httpd state=reloaded

- name: Play3 - Install Python
  hosts: webservers
  become: yes
  tasks:
    - name: Installing python 3.6
      ansible.builtin.yum:
        name: python36
        state: present
      tags: python-install

    - name: alternatives
      community.general.alternatives:
        name: python
        link: /usr/bin/python3.6
        path: /usr/bin/python3
      tags: python-alternatives

- name: Play4 - Python library istall and copying of war file (Install boto and botocore with pip3 module (these requirements are needed on the host that executes this module.aws s3 module))
  hosts: webservers
  become: yes
  vars:
    ansible-python-interpreter: /usr/bin/python
  tasks:
    - name: Install boto and botocore with pip3 module
      ansible.builtin.pip:
        name:
          - boto
          - boto3
          - botocore
        executable: pip3.6
      tags: boto-lib-install

    - name: copy of war file
      amazon.aws.aws_s3:
        bucket: emotionalbucket
        object: login##1.0.war
        dest: /etc/tomcat/webapps/login##1.0.war
        mode: get
      tags: copy-war-from-s3-to-node

- name: Play5 - starting of tomcat server
  hosts: webservers
  become: yes
  tasks:
        #name: shutdown tomcat
        #command: nohup sh /etc/tomcat/shutdown.sh
    - name: start tomcat
      ansible.builtin.command: nohup sh /etc/tomcat/bin/startup.sh
      tags: start-tomcat
