
- name: Unarchive a tomcat tar from tomcat website
  ansible.builtin.unarchive:
    src: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.81/bin/apache-tomcat-8.5.81.tar.gz
    dest: /etc/
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  tags:
   - tar-copy

- name: create a soft link to the tomcat folder
  ansible.builtin.file:
    src: /etc/apache-tomcat-8.5.81
    dest: /etc/tomcat
    owner: root
    group: root
    state: link
  tags:
    - softlink
